-- VHDL Entity alien_game_lib.c1_t1_half_adder.symbol
--
-- Created:
--          by - vrming.vrming (linux-desktop1.tuni.fi)
--          at - 11:05:18 09/12/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c1_t1_half_adder IS
   PORT( 
      sw0   : IN     std_logic;
      sw1   : IN     std_logic;
      carry : OUT    std_logic;
      sum   : OUT    std_logic
   );

-- Declarations

END c1_t1_half_adder ;

--
-- VHDL Architecture alien_game_lib.c1_t1_half_adder.struct
--
-- Created:
--          by - vrming.vrming (linux-desktop1.tuni.fi)
--          at - 12:31:11 09/12/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c1_t1_half_adder IS

   -- Architecture declarations

   -- Internal signal declarations



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'and1'
   carry <= sw1 AND sw0;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'sxor'
   sum <= sw0 XOR sw1;

   -- Instance port mappings.

END struct;
