-- VHDL Entity alien_game_lib.c1_t3_decrementer.symbol
--
-- Created:
--          by - fmthng.fmthng (linux-desktop7.tuni.fi)
--          at - 20:28:22 09/15/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c1_t3_decrementer IS
   PORT( 
      value  : IN     std_logic_vector (2 DOWNTO 0);
      result : OUT    std_logic_vector (2 DOWNTO 0)
   );

-- Declarations

END c1_t3_decrementer ;

--
-- VHDL Architecture alien_game_lib.c1_t3_decrementer.struct
--
-- Created:
--          by - fmthng.fmthng (linux-desktop7.tuni.fi)
--          at - 20:28:22 09/15/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c1_t3_decrementer IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL din1  : std_logic;
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic;
   SIGNAL dout3 : std_logic;
   SIGNAL dout4 : std_logic;
   SIGNAL dout6 : std_logic;
   SIGNAL dout7 : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL result_internal : std_logic_vector (2 DOWNTO 0);



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_1' of 'and'
   dout1 <= result_internal(0) AND dout;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'and'
   dout2 <= value(0) AND value(1);

   -- ModuleWare code(v1.12) for instance 'U_5' of 'and'
   dout3 <= value(1) AND value(2);

   -- ModuleWare code(v1.12) for instance 'U_8' of 'and'
   dout6 <= dout1 AND dout4;

   -- ModuleWare code(v1.12) for instance 'U_10' of 'and'
   din1 <= value(0) AND value(2);

   -- ModuleWare code(v1.12) for instance 'U_0' of 'inv'
   result_internal(0) <= NOT(value(0));

   -- ModuleWare code(v1.12) for instance 'U_3' of 'inv'
   dout <= NOT(value(1));

   -- ModuleWare code(v1.12) for instance 'U_7' of 'inv'
   dout4 <= NOT(value(2));

   -- ModuleWare code(v1.12) for instance 'U_2' of 'or'
   result_internal(1) <= dout1 OR dout2;

   -- ModuleWare code(v1.12) for instance 'U_9' of 'or'
   dout7 <= dout3 OR dout6;

   -- ModuleWare code(v1.12) for instance 'U_11' of 'or'
   result_internal(2) <= dout7 OR din1;

   -- Instance port mappings.

   -- Implicit buffered output assignments
   result <= result_internal;

END struct;
