-- VHDL Entity alien_game_lib.c1_t2_incrementer.symbol
--
-- Created:
--          by - vrming.vrming (linux-desktop9.tuni.fi)
--          at - 19:51:14 09/14/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c1_t2_incrementer IS
   PORT( 
      value  : IN     std_logic_vector (2 DOWNTO 0);
      result : OUT    std_logic_vector (2 DOWNTO 0)
   );

-- Declarations

END c1_t2_incrementer ;

--
-- VHDL Architecture alien_game_lib.c1_t2_incrementer.struct
--
-- Created:
--          by - vrming.vrming (linux-desktop4.tuni.fi)
--          at - 17:31:25 09/15/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c1_t2_incrementer IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic;
   SIGNAL dout3 : std_logic;
   SIGNAL dout4 : std_logic;
   SIGNAL dout5 : std_logic;
   SIGNAL dout6 : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL result_internal : std_logic_vector (2 DOWNTO 0);



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_3' of 'and'
   dout2 <= value(0) AND dout;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'and'
   dout3 <= value(1) AND result_internal(0);

   -- ModuleWare code(v1.12) for instance 'U_6' of 'and'
   dout4 <= value(2) AND result_internal(0);

   -- ModuleWare code(v1.12) for instance 'U_7' of 'and'
   dout5 <= value(2) AND dout;

   -- ModuleWare code(v1.12) for instance 'U_8' of 'and'
   dout6 <= dout1 AND value(1) AND value(0);

   -- ModuleWare code(v1.12) for instance 'U_0' of 'inv'
   result_internal(0) <= NOT(value(0));

   -- ModuleWare code(v1.12) for instance 'U_1' of 'inv'
   dout <= NOT(value(1));

   -- ModuleWare code(v1.12) for instance 'U_2' of 'inv'
   dout1 <= NOT(value(2));

   -- ModuleWare code(v1.12) for instance 'U_4' of 'or'
   result_internal(1) <= dout2 OR dout3;

   -- ModuleWare code(v1.12) for instance 'U_9' of 'or'
   result_internal(2) <= dout4 OR dout5 OR dout6;

   -- Instance port mappings.

   -- Implicit buffered output assignments
   result <= result_internal;

END struct;
