-- VHDL Entity alien_game_lib.c2_t1_combined.symbol
--
-- Created:
--          by - vrming.vrming (linux-desktop12.tuni.fi)
--          at - 18:30:26 09/29/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t1_combined IS
   PORT( 
      btn       : IN     std_logic_vector (3 DOWNTO 0);
      sw0       : IN     std_logic;
      color_BGR : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord   : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord   : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c2_t1_combined ;

--
-- VHDL Architecture alien_game_lib.c2_t1_combined.struct
--
-- Created:
--          by - vrming.vrming (linux-desktop12.tuni.fi)
--          at - 18:30:26 09/29/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c2_t1_combined IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL color_BGR1 : std_logic_vector(23 DOWNTO 0);
   SIGNAL color_BGR2 : std_logic_vector(23 DOWNTO 0);
   SIGNAL x_coord1   : std_logic_vector(7 DOWNTO 0);
   SIGNAL x_coord2   : std_logic_vector(7 DOWNTO 0);
   SIGNAL y_coord1   : std_logic_vector(7 DOWNTO 0);
   SIGNAL y_coord2   : std_logic_vector(7 DOWNTO 0);


   -- Component Declarations
   COMPONENT c2_t1_interactive
   PORT (
      btn       : IN     std_logic_vector (3 DOWNTO 0);
      color_BGR : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord   : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord   : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT c2_t1_static
   PORT (
      color_BGR : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord   : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord   : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c2_t1_interactive USE ENTITY alien_game_lib.c2_t1_interactive;
   FOR ALL : c2_t1_static USE ENTITY alien_game_lib.c2_t1_static;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_1' of 'mux'
   u_1combo_proc: PROCESS(x_coord1, x_coord2, sw0)
   BEGIN
      CASE sw0 IS
      WHEN '0' => x_coord <= x_coord1;
      WHEN '1' => x_coord <= x_coord2;
      WHEN OTHERS => x_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_1combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'mux'
   u_2combo_proc: PROCESS(y_coord1, y_coord2, sw0)
   BEGIN
      CASE sw0 IS
      WHEN '0' => y_coord <= y_coord1;
      WHEN '1' => y_coord <= y_coord2;
      WHEN OTHERS => y_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_2combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'mux'
   u_3combo_proc: PROCESS(color_BGR1, color_BGR2, sw0)
   BEGIN
      CASE sw0 IS
      WHEN '0' => color_BGR <= color_BGR1;
      WHEN '1' => color_BGR <= color_BGR2;
      WHEN OTHERS => color_BGR <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_3combo_proc;

   -- Instance port mappings.
   U_4 : c2_t1_interactive
      PORT MAP (
         btn       => btn,
         color_BGR => color_BGR2,
         x_coord   => x_coord2,
         y_coord   => y_coord2
      );
   U_0 : c2_t1_static
      PORT MAP (
         color_BGR => color_BGR1,
         x_coord   => x_coord1,
         y_coord   => y_coord1
      );

END struct;
