-- VHDL Entity alien_game_lib.c2_t1_interactive.symbol
--
-- Created:
--          by - vrming.vrming (linux-desktop12.tuni.fi)
--          at - 18:07:40 09/29/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t1_interactive IS
   PORT( 
      btn       : IN     std_logic_vector (3 DOWNTO 0);
      color_BGR : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord   : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord   : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c2_t1_interactive ;

--
-- VHDL Architecture alien_game_lib.c2_t1_interactive.struct
--
-- Created:
--          by - vrming.vrming (linux-desktop12.tuni.fi)
--          at - 18:07:40 09/29/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c2_t1_interactive IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout   : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout1  : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout10 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout11 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout12 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout2  : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout3  : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout4  : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout5  : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout6  : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout7  : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout9  : std_logic_vector(7 DOWNTO 0);



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_2' of 'constval'
   dout4 <= x"FF0000";

   -- ModuleWare code(v1.12) for instance 'U_3' of 'constval'
   dout5 <= x"0FF0F0";

   -- ModuleWare code(v1.12) for instance 'U_4' of 'constval'
   dout6 <= x"00FF00";

   -- ModuleWare code(v1.12) for instance 'U_5' of 'constval'
   dout7 <= x"FF0000";

   -- ModuleWare code(v1.12) for instance 'U_6' of 'constval'
   dout <= x"01";

   -- ModuleWare code(v1.12) for instance 'U_7' of 'constval'
   dout1 <= x"02";

   -- ModuleWare code(v1.12) for instance 'U_8' of 'constval'
   dout2 <= x"04";

   -- ModuleWare code(v1.12) for instance 'U_9' of 'constval'
   dout3 <= x"08";

   -- ModuleWare code(v1.12) for instance 'U_12' of 'constval'
   dout9 <= x"03";

   -- ModuleWare code(v1.12) for instance 'U_13' of 'constval'
   dout10 <= x"04";

   -- ModuleWare code(v1.12) for instance 'U_14' of 'constval'
   dout11 <= x"07";

   -- ModuleWare code(v1.12) for instance 'U_15' of 'constval'
   dout12 <= x"30";

   -- ModuleWare code(v1.12) for instance 'U_0' of 'omux'
   u_0combo_proc: PROCESS(dout, dout1, dout2, dout3, btn)
   BEGIN
      x_coord <= (OTHERS => 'X');
      CASE btn IS
      WHEN "0001" => x_coord <= dout;
      WHEN "0010" => x_coord <= dout1;
      WHEN "0100" => x_coord <= dout2;
      WHEN "1000" => x_coord <= dout3;
      WHEN OTHERS => x_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_0combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'omux'
   u_1combo_proc: PROCESS(dout4, dout5, dout6, dout7, btn)
   BEGIN
      color_BGR <= (OTHERS => 'X');
      IF (btn(0) = '1') THEN
         color_BGR <= dout4;
      ELSIF (btn(1) = '1') THEN
         color_BGR <= dout5;
      ELSIF (btn(2) = '1') THEN
         color_BGR <= dout6;
      ELSIF (btn(3) = '1') THEN
         color_BGR <= dout7;
      ELSE
         color_BGR <= (OTHERS => 'X');
      END IF;
   END PROCESS u_1combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_11' of 'omux'
   u_11combo_proc: PROCESS(dout9, dout10, dout11, dout12, btn)
   BEGIN
      y_coord <= (OTHERS => 'X');
      CASE btn IS
      WHEN "0001" => y_coord <= dout9;
      WHEN "0010" => y_coord <= dout10;
      WHEN "0100" => y_coord <= dout11;
      WHEN "1000" => y_coord <= dout12;
      WHEN OTHERS => y_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_11combo_proc;

   -- Instance port mappings.

END struct;
