-- VHDL Entity alien_game_lib.c2_t4_right_shifter.symbol
--
-- Created:
--          by - mmledo.mmledo (linux-desktop8.tuni.fi)
--          at - 17:22:48 10/02/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t4_right_shifter IS
   PORT( 
      data_in  : IN     std_logic_vector (7 DOWNTO 0);
      data_out : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c2_t4_right_shifter ;

--
-- VHDL Architecture alien_game_lib.c2_t4_right_shifter.tbl
--
-- Created:
--          by - mmledo.mmledo (linux-desktop8.tuni.fi)
--          at - 19:49:15 10/02/20
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
ARCHITECTURE tbl OF c2_t4_right_shifter IS
   
      -- Architecture declarations
    

BEGIN

   -----------------------------------------------------------------
   truth_process_proc: PROCESS(data_in)
   -----------------------------------------------------------------
   BEGIN
      -- Block 1
      IF (data_in = "00000001") THEN
         data_out <= "00000000";
      ELSIF (data_in = "00000010") THEN
         data_out <= "00000001";
      ELSIF (data_in = "00000100") THEN
         data_out <= "00000010";
      ELSIF (data_in = "00001000") THEN
         data_out <= "00000100";
      ELSIF (data_in = "00010000") THEN
         data_out <= "00001000";
      ELSIF (data_in = "00100000") THEN
         data_out <= "00010000";
      ELSIF (data_in = "01000000") THEN
         data_out <= "00100000";
      ELSIF (data_in = "00000000") THEN
         data_out <= "00000000";
      ELSIF (data_in = "10000000") THEN
         data_out <= "01000000";
      END IF;

   END PROCESS truth_process_proc;

-- Architecture concurrent statements
 

END tbl;
