-- VHDL Entity alien_game_lib.c3_t1_gun_module.symbol
--
-- Created:
--          by - Minh.UNKNOWN (DESKTOP-R6EVFEE)
--          at - 13:12:39 10/10/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c3_t1_gun_module IS
   PORT( 
      btn        : IN     std_logic_vector (3 DOWNTO 0);
      clk        : IN     std_logic;
      enable     : IN     std_logic;
      gun_px_idx : IN     std_logic_vector (1 DOWNTO 0);
      rst_n      : IN     std_logic;
      Gun_color  : OUT    std_logic_vector (23 DOWNTO 0);
      X_coord    : OUT    std_logic_vector (7 DOWNTO 0);
      Y_coord    : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c3_t1_gun_module ;

--
-- VHDL Architecture alien_game_lib.c3_t1_gun_module.struct
--
-- Created:
--          by - Minh.UNKNOWN (DESKTOP-R6EVFEE)
--          at - 13:21:06 12/ 6/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c3_t1_gun_module IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout1       : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout15      : std_logic;
   SIGNAL dout16      : std_logic;
   SIGNAL dout3       : std_logic;
   SIGNAL dout4       : std_logic_vector(7 DOWNTO 0);
   SIGNAL left_shift  : std_logic;                       -- left-shift
   SIGNAL right_shift : std_logic;
   SIGNAL sel_val     : std_logic_vector(1 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL X_coord_internal : std_logic_vector (7 DOWNTO 0);


   -- Component Declarations
   COMPONENT c3_t1_gun_module_x_coord
   PORT (
      clk        : IN     std_logic ;
      gun_px_idx : IN     std_logic_vector (1 DOWNTO 0);
      rst_n      : IN     std_logic ;
      sel_val    : IN     std_logic_vector (1 DOWNTO 0);
      X_coord    : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c3_t1_gun_module_x_coord USE ENTITY alien_game_lib.c3_t1_gun_module_x_coord;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_6' of 'and'
   left_shift <= NOT(dout15) AND btn(1) AND enable;

   -- ModuleWare code(v1.12) for instance 'U_9' of 'and'
   dout3 <= gun_px_idx(0) AND gun_px_idx(1);

   -- ModuleWare code(v1.12) for instance 'U_15' of 'and'
   right_shift <= btn(3) AND enable AND NOT(dout16);

   -- ModuleWare code(v1.12) for instance 'U_3' of 'constval'
   dout1 <= x"80";

   -- ModuleWare code(v1.12) for instance 'U_8' of 'constval'
   dout4 <= x"40";

   -- ModuleWare code(v1.12) for instance 'U_26' of 'constval'
   Gun_color <= x"808080";

   -- ModuleWare code(v1.12) for instance 'U_7' of 'merge'
   sel_val <= right_shift & left_shift;

   -- ModuleWare code(v1.12) for instance 'U_10' of 'mux'
   u_10combo_proc: PROCESS(dout1, dout4, dout3)
   BEGIN
      CASE dout3 IS
      WHEN '0' => Y_coord <= dout1;
      WHEN '1' => Y_coord <= dout4;
      WHEN OTHERS => Y_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_10combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_28' of 'mux'
   u_28combo_proc: PROCESS(X_coord_internal, gun_px_idx)
   BEGIN
      CASE gun_px_idx IS
      WHEN "00" => dout15 <= X_coord_internal(7);
      WHEN "01" => dout15 <= X_coord_internal(6);
      WHEN "10" => dout15 <= X_coord_internal(5);
      WHEN "11" => dout15 <= X_coord_internal(6);
      WHEN OTHERS => dout15 <= 'X';
      END CASE;
   END PROCESS u_28combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_29' of 'mux'
   u_29combo_proc: PROCESS(X_coord_internal, gun_px_idx)
   BEGIN
      CASE gun_px_idx IS
      WHEN "00" => dout16 <= X_coord_internal(2);
      WHEN "01" => dout16 <= X_coord_internal(1);
      WHEN "10" => dout16 <= X_coord_internal(0);
      WHEN "11" => dout16 <= X_coord_internal(1);
      WHEN OTHERS => dout16 <= 'X';
      END CASE;
   END PROCESS u_29combo_proc;

   -- Instance port mappings.
   U_0 : c3_t1_gun_module_x_coord
      PORT MAP (
         clk        => clk,
         gun_px_idx => gun_px_idx,
         rst_n      => rst_n,
         sel_val    => sel_val,
         X_coord    => X_coord_internal
      );

   -- Implicit buffered output assignments
   X_coord <= X_coord_internal;

END struct;
