-- VHDL Entity alien_game_lib.c5_t3_debounce.symbol
--
-- Created:
--          by - Minh.UNKNOWN (DESKTOP-R6EVFEE)
--          at - 10:38:32 11/23/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c5_t3_debounce IS
   PORT( 
      btn_in  : IN     std_logic;
      clk     : IN     std_logic;
      rst_n   : IN     std_logic;
      btn_out : OUT    std_logic
   );

-- Declarations

END c5_t3_debounce ;

--
-- VHDL Architecture alien_game_lib.c5_t3_debounce.struct
--
-- Created:
--          by - Minh.UNKNOWN (DESKTOP-R6EVFEE)
--          at - 10:38:32 11/23/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c5_t3_debounce IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic;
   SIGNAL dout3 : std_logic;
   SIGNAL q     : std_logic;
   SIGNAL q1    : std_logic;
   SIGNAL q2    : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'adff'
   SIGNAL mw_U_0reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.12) for instance 'U_2' of 'adff'
   SIGNAL mw_U_2reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.12) for instance 'U_3' of 'adff'
   SIGNAL mw_U_3reg_cval : std_logic;


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'adff'
   q <= mw_U_0reg_cval;
   u_0seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_0reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_0reg_cval <= btn_in;
      END IF;
   END PROCESS u_0seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'adff'
   q2 <= mw_U_2reg_cval;
   u_2seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_2reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_2reg_cval <= dout;
      END IF;
   END PROCESS u_2seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'adff'
   q1 <= mw_U_3reg_cval;
   u_3seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_3reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_3reg_cval <= q2;
      END IF;
   END PROCESS u_3seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'and'
   dout <= q AND btn_in;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'clkdiv'

   -- ModuleWare code(v1.12) for instance 'U_5_value_0' of 'constval'
   dout3 <= '0';

   -- ModuleWare code(v1.12) for instance 'U_4' of 'mux'
   u_4combo_proc: PROCESS(q2, dout3, q1)
   BEGIN
      CASE q1 IS
      WHEN '0' => btn_out <= q2;
      WHEN '1' => btn_out <= dout3;
      WHEN OTHERS => btn_out <= 'X';
      END CASE;
   END PROCESS u_4combo_proc;

   -- Instance port mappings.

END struct;
