-- VHDL Entity alien_game_lib.c5_t1_hit_detector.symbol
--
-- Created:
--          by - Minh.UNKNOWN (DESKTOP-R6EVFEE)
--          at - 21:14:29 12/ 6/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c5_t1_hit_detector IS
   PORT( 
      alien_x  : IN     std_logic_vector (7 DOWNTO 0);
      alien_y  : IN     std_logic_vector (7 DOWNTO 0);
      btn      : IN     std_logic;
      bullet_x : IN     std_logic_vector (7 DOWNTO 0);
      bullet_y : IN     std_logic_vector (7 DOWNTO 0);
      clk      : IN     std_logic;
      gun_x    : IN     std_logic_vector (7 DOWNTO 0);
      mode_in  : IN     std_logic;
      rst_n    : IN     std_logic;
      hit      : OUT    std_logic
   );

-- Declarations

END c5_t1_hit_detector ;

--
-- VHDL Architecture alien_game_lib.c5_t1_hit_detector.struct
--
-- Created:
--          by - Minh.UNKNOWN (DESKTOP-R6EVFEE)
--          at - 21:14:29 12/ 6/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c5_t1_hit_detector IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL din1   : std_logic;
   SIGNAL dout   : std_logic;
   SIGNAL dout1  : std_logic;
   SIGNAL dout2  : std_logic;
   SIGNAL q      : std_logic;
   SIGNAL r_out  : std_logic;
   SIGNAL r_out1 : std_logic;
   SIGNAL r_out2 : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_5' of 'adff'
   SIGNAL mw_U_5reg_cval : std_logic;

   -- Component Declarations
   COMPONENT c5_t1_8_bit_comparator
   PORT (
      a_in  : IN     std_logic_vector (7 DOWNTO 0);
      b_in  : IN     std_logic_vector (7 DOWNTO 0);
      r_out : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c5_t1_8_bit_comparator USE ENTITY alien_game_lib.c5_t1_8_bit_comparator;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_5' of 'adff'
   q <= mw_U_5reg_cval;
   u_5seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_5reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_5reg_cval <= dout2;
      END IF;
   END PROCESS u_5seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'and'
   dout <= r_out1 AND r_out2;

   -- ModuleWare code(v1.12) for instance 'U_6' of 'and'
   dout2 <= dout1 AND btn;

   -- ModuleWare code(v1.12) for instance 'U_8' of 'constval'
   din1 <= '0';

   -- ModuleWare code(v1.12) for instance 'U_0' of 'mux'
   u_0combo_proc: PROCESS(r_out, dout, mode_in)
   BEGIN
      CASE mode_in IS
      WHEN '0' => dout1 <= r_out;
      WHEN '1' => dout1 <= dout;
      WHEN OTHERS => dout1 <= 'X';
      END CASE;
   END PROCESS u_0combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_7' of 'mux'
   u_7combo_proc: PROCESS(dout2, din1, q)
   BEGIN
      CASE q IS
      WHEN '0' => hit <= dout2;
      WHEN '1' => hit <= din1;
      WHEN OTHERS => hit <= 'X';
      END CASE;
   END PROCESS u_7combo_proc;

   -- Instance port mappings.
   U_1 : c5_t1_8_bit_comparator
      PORT MAP (
         a_in  => alien_x,
         b_in  => gun_x,
         r_out => r_out
      );
   U_2 : c5_t1_8_bit_comparator
      PORT MAP (
         a_in  => bullet_x,
         b_in  => alien_x,
         r_out => r_out1
      );
   U_3 : c5_t1_8_bit_comparator
      PORT MAP (
         a_in  => bullet_y,
         b_in  => alien_y,
         r_out => r_out2
      );

END struct;
