-- VHDL Entity alien_game_lib.c6_t2_alien_health.symbol
--
-- Created:
--          by - Minh.UNKNOWN (DESKTOP-R6EVFEE)
--          at - 00:29:48 12/ 7/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c6_t2_alien_health IS
   PORT( 
      clk          : IN     std_logic;
      hit_in       : IN     std_logic;
      rst_n        : IN     std_logic;
      defeated_out : OUT    std_logic;
      health_out   : OUT    std_logic_vector (1 DOWNTO 0)
   );

-- Declarations

END c6_t2_alien_health ;

--
-- VHDL Architecture alien_game_lib.c6_t2_alien_health.struct
--
-- Created:
--          by - Minh.UNKNOWN (DESKTOP-R6EVFEE)
--          at - 00:29:48 12/ 7/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c6_t2_alien_health IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL data_out : std_logic_vector(1 DOWNTO 0);
   SIGNAL dout     : std_logic_vector(1 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL health_out_internal : std_logic_vector (1 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'adff'
   SIGNAL mw_U_0reg_cval : std_logic_vector(1 DOWNTO 0);

   -- Component Declarations
   COMPONENT c6_t2_decremeter_length_two
   PORT (
      data_in  : IN     std_logic_vector (1 DOWNTO 0);
      data_out : OUT    std_logic_vector (1 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c6_t2_decremeter_length_two USE ENTITY alien_game_lib.c6_t2_decremeter_length_two;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'adff'
   health_out_internal <= mw_U_0reg_cval;
   u_0seq_proc: PROCESS (clk)BEGIN
      IF (clk'EVENT AND clk='1') THEN
         IF (rst_n = '0') THEN
            mw_U_0reg_cval <= "11";
         ELSE
            mw_U_0reg_cval <= dout;
         END IF;
      END IF;
   END PROCESS u_0seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'and'
   defeated_out <= NOT(health_out_internal(1))
                   AND NOT(health_out_internal(0));

   -- ModuleWare code(v1.12) for instance 'U_2' of 'mux'
   u_2combo_proc: PROCESS(health_out_internal, data_out, hit_in)
   BEGIN
      CASE hit_in IS
      WHEN '0' => dout <= health_out_internal;
      WHEN '1' => dout <= data_out;
      WHEN OTHERS => dout <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_2combo_proc;

   -- Instance port mappings.
   U_1 : c6_t2_decremeter_length_two
      PORT MAP (
         data_in  => health_out_internal,
         data_out => data_out
      );

   -- Implicit buffered output assignments
   health_out <= health_out_internal;

END struct;
